### ISSUE TITLE
Include MCP23008?

### ISSUE THREAD

**Issue by Joe-ab1do** [PizzaProgram/MCP23017-PCF8574-AIO#2]
I was just wondering how easy it would be to include the MCP23008, which like the PCF8574 is an 8 GPIO port expander. Essentially the MCP23008 is equivalent to half an MCP23017: it uses the same addressing configuration and from a quick scan of the datasheets it would seem that it is equal to an MCP23017 but with only GPA0-7 included and not GPB8-15. Register addressing seems pretty much the same if everything relating to the GPB ports is excluded.

I have several boards using mcp23008s, hence my interest. And it would certainly expand the applicability of your nodes.

What I really like about this project is that unlike many others relating to these chips all the code is written in nodejs or html, making it very accessible.

Thanks,
Joe

**Comment by PizzaProgram** [comment]
I was afraid this question will happen. :-D

Sorry, not possible to overcomplicate the code even further right know.

# Reasons:

1. it took me 14 month to finish it.
2. it's working now, have to go back doing my real work, and install these chips to my house so I can finally "turn on some things" after 2 years of "darkness". (Dry lightning killed every electronics in my smart-home 2 years ago.)
3. Debugging is not working. So a 5 minute error-search takes sometimes 2 weeks.
4. I don't have any MCP23008 and I've checked both the shops I usually order from. (Not that I would buy them, if there were any, because I get double so much pins with MCP23016 for +10% price.
5. MCP23016 chips are very cheap. That's why I have chosen those. You may think about switching to those kind.
6. Currently a code is distinguishing the different kind of chips with address range. (doubled the PCF) So an other MCP would conflict with current MCP chip. We would need to completely re-arrange everything everywhere.

# Hope

Of course you can TRY to use it with this code, because if it's similar, than it may work. Theoretically it should work, because I've compared the 2 chip's PDF files and the most important part is the same:
```
	const BNK1_GPIO_A    = 0x09;
	const BNK1_OLAT_A    = 0x0A;
```
But I can not guarantee anything. ;-)

# Tip:

- When you try it, do not use direct interrupt, because it will try to read both banks.
- Use only the nodes placed and pre-configured to 0-7

**Comment by PizzaProgram** [comment]
Of course, if you are a Javascript expert, and would like to do the whole job alone, you are welcome to do it :-)
I'll commit.

I only ask for one thing:
 - please comment properly all the lines, like I have done it
 - and leave 4 spaces (tabs) for intent.

**Comment by Joe-ab1do** [comment]
Thanks for the expansive answer and I'll take a look at it in a little more depth. Fully understand the MCP23017 vs MCP23008 issue, and frankly if I were building the hardware today I would probably choose the MCP23017 also, but I am currently using somewhat dated 16 relay boards with 2 23008s where 1 23017 would have sufficed.

Addressing would not be an issue: matter of making sure none are on the same address, or using multiple buses: one for the 23008s and one for the 223017. I currently run 3 i2c buses on a Raspberry PI, so....

GL on getting the house lit up again!
